using System;
using System.Globalization;
using System.Text;

namespace OpenHintSQL.ResultGridScripting
{
    /// <summary>
    /// Builds the complete CREATE TABLE + INSERT script from a selection
    /// matrix. Output is deterministic and self-contained — paste it into a
    /// fresh tab and it runs.
    ///
    /// SQL Server caps row-constructor inserts at 1000 rows per VALUES list,
    /// so larger selections split into multiple INSERT statements.
    /// </summary>
    internal static class InsertScriptBuilder
    {
        private const int MaxRowsPerInsert = 1000;
        public const string DefaultTempTableName = "#TempTable";

        public static string Build(string[] headers, string[,] values, string tempTableName = DefaultTempTableName)
        {
            if (headers == null) throw new ArgumentNullException(nameof(headers));
            if (values == null) throw new ArgumentNullException(nameof(values));

            long rowCount = values.GetLongLength(0);
            int colCount = values.GetLength(1);
            if (headers.Length != colCount)
                throw new ArgumentException("Header count does not match value column count.");

            var inferred = new InferredSqlType[colCount];
            for (int c = 0; c < colCount; c++)
                inferred[c] = SqlTypeInferer.Infer(values, c);

            var sb = new StringBuilder(capacity: (int)Math.Min(int.MaxValue, 256L + rowCount * 64L * colCount));

            AppendHeader(sb, rowCount, colCount);
            AppendCreateTable(sb, headers, inferred, tempTableName);
            AppendInsertStatements(sb, headers, values, inferred, rowCount, colCount, tempTableName);

            return sb.ToString();
        }

        private static void AppendHeader(StringBuilder sb, long rowCount, int colCount)
        {
            sb.Append("-- Generated by OpenHint SQL on ")
              .Append(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture))
              .AppendLine();
            sb.Append("-- ").Append(rowCount).Append(" row(s), ").Append(colCount).AppendLine(" column(s)");
            sb.AppendLine("-- Column types are inferred heuristically from the selection — adjust if needed.");
            sb.AppendLine();
        }

        private static void AppendCreateTable(StringBuilder sb, string[] headers, InferredSqlType[] inferred, string tempTableName)
        {
            sb.Append("IF OBJECT_ID('tempdb..").Append(tempTableName).Append("') IS NOT NULL DROP TABLE ").Append(tempTableName).AppendLine(";");
            sb.AppendLine();
            sb.Append("CREATE TABLE ").Append(tempTableName).AppendLine();
            sb.AppendLine("(");

            int colPadding = MaxColumnQuotedWidth(headers);
            for (int c = 0; c < headers.Length; c++)
            {
                string quoted = SqlTypeInferer.QuoteIdentifier(headers[c]);
                sb.Append("    ").Append(quoted.PadRight(colPadding)).Append(' ').Append(SqlTypeInferer.SqlTypeDeclaration(inferred[c]));
                if (c < headers.Length - 1) sb.Append(',');
                sb.AppendLine();
            }
            sb.AppendLine(");");
            sb.AppendLine();
        }

        private static void AppendInsertStatements(
            StringBuilder sb,
            string[] headers,
            string[,] values,
            InferredSqlType[] inferred,
            long rowCount,
            int colCount,
            string tempTableName)
        {
            if (rowCount == 0)
                return;

            string columnList = BuildColumnList(headers);

            long offset = 0;
            while (offset < rowCount)
            {
                long batchSize = Math.Min(MaxRowsPerInsert, rowCount - offset);

                sb.Append("INSERT INTO ").Append(tempTableName).Append(" (").Append(columnList).AppendLine(") VALUES");

                for (long r = 0; r < batchSize; r++)
                {
                    long row = offset + r;
                    sb.Append("    (");
                    for (int c = 0; c < colCount; c++)
                    {
                        if (c > 0) sb.Append(", ");
                        sb.Append(SqlTypeInferer.EmitLiteral(values[row, c], inferred[c]));
                    }
                    sb.Append(')');
                    sb.AppendLine(r == batchSize - 1 ? ";" : ",");
                }

                offset += batchSize;
                if (offset < rowCount)
                    sb.AppendLine();
            }
        }

        private static string BuildColumnList(string[] headers)
        {
            var sb = new StringBuilder();
            for (int c = 0; c < headers.Length; c++)
            {
                if (c > 0) sb.Append(", ");
                sb.Append(SqlTypeInferer.QuoteIdentifier(headers[c]));
            }
            return sb.ToString();
        }

        private static int MaxColumnQuotedWidth(string[] headers)
        {
            int max = 0;
            foreach (var h in headers)
            {
                int w = SqlTypeInferer.QuoteIdentifier(h).Length;
                if (w > max) max = w;
            }
            return max;
        }
    }
}
